// SourceRadar curated picks — data model driven by docs/STRATEGY.md.
// Prices in USD. price1688 = domestic wholesale (converted), priceAlibaba = typical
// Alibaba listing, retailPrice = US/EU street price. tariffUS = combined ad-valorem
// estimate for 2026 (MFN + S301 + baseline layers). freightUnit = est. sea freight
// per unit (USD). lifecycle: early | growth | saturated (vs Western market).
const PRODUCTS = [
  // ── PROFIT TIER ─────────────────────────────────────────────
  {
    id: "led-mask",
    name: "Red-Light LED Therapy Mask",
    emoji: "🎭",
    track: "Beauty Devices",
    tier: "profit",
    price1688: [14, 28],
    priceAlibaba: [20, 38],
    retailPrice: [89, 299],
    cnKeyword: "红光美容面罩 LED",
    trendQuery: "red light therapy mask",
    moq: 100,
    trendScore: 97,
    lifecycle: "growth",
    chinaSignal: "Factory ecosystem matured on 1688 through 2024–25; Douyin beauty-device content normalized the category before Western creators picked it up.",
    signals: ["TikTok Shop beauty devices +400%", "\"red light therapy mask\" searches +264% in 6 months", "26% of purchases happen in TikTok livestreams"],
    compliance: {
      us: ["FDA: stay in \"general wellness\" claims territory", "FCC", "UN38.3 + MSDS (battery)"],
      eu: ["CE (LVD/EMC)", "IEC 60601-2-57 photobiological safety report", "GPSR responsible person"],
      difficulty: "high",
      note: "The moat cuts both ways: FTC has issued warning letters over red-light claims (2024–25) and Health Canada recalled a mask in 2025. Source only FDA 510(k)-cleared designs with eye protection; keep claims to cleared indications (acne, fine lines)."
    },
    tariffUS: 0.33,
    freightUnit: 1.2,
    freightMode: "Air OK with battery docs · small parcel",
    season: "Q4 gifting peak (Nov–Dec is annual high)",
    orderBy: "August",
    risks: "FTC warning letters and a Health Canada recall hit this category in 2025; $59 uncleared white-labels are crashing the price floor. Overclaiming (fat-loss/anti-aging) is the #1 enforcement trigger; weak LEDs drive refunds.",
    whyHot: "5–10× factory-to-retail spread with premium brands anchoring $300–500 price points overhead.",
    buyerTip: "Demand a photobiological safety test report and per-wavelength irradiance data. Ship with goggles."
  },
  {
    id: "pet-fountain",
    name: "Wireless-Pump Pet Water Fountain",
    emoji: "🐱",
    track: "Smart Pet",
    tier: "profit",
    price1688: [4.5, 9],
    priceAlibaba: [6, 12],
    retailPrice: [30, 60],
    cnKeyword: "宠物饮水机 无线水泵",
    trendQuery: "pet water fountain",
    moq: 300,
    trendScore: 88,
    lifecycle: "growth",
    chinaSignal: "Petkit-style wireless-pump designs iterated in China's domestic market first; ~half of Petkit's ¥1.1B revenue is now export across 40+ countries.",
    signals: ["Fountain market $183M → $427M by 2035", "North America is the largest market", "Filter refills = recurring revenue"],
    compliance: {
      us: ["FCC", "FDA food-contact materials"],
      eu: ["CE/RoHS", "GPSR responsible person"],
      difficulty: "low",
      note: "Low-friction category — one of the easiest profitable entries."
    },
    tariffUS: 0.33,
    freightUnit: 1.5,
    freightMode: "Sea for margin · mid-size parcel",
    season: "Year-round stable, slight summer peak",
    orderBy: "Any month",
    risks: "Pump noise >30dB and pump-in-water cleaning pain are the review killers — wireless pump solves both.",
    whyHot: "3–5× spread, structural pet-economy growth, and a filter-subscription backend.",
    buyerTip: "Private-label the filters — that's where durable margin lives. Verify 2L+ capacity."
  },
  {
    id: "pet-feeder",
    name: "Smart Pet Feeder with Camera",
    emoji: "📹",
    track: "Smart Pet",
    tier: "profit",
    price1688: [14, 24],
    priceAlibaba: [18, 32],
    retailPrice: [60, 120],
    cnKeyword: "宠物自动喂食器 摄像头",
    trendQuery: "automatic pet feeder camera",
    moq: 200,
    trendScore: 86,
    lifecycle: "growth",
    chinaSignal: "Camera-feeder combos standard in China's domestic pet market a full product generation before Western shelves.",
    signals: ["Smart feeder market $2.61B → $7.56B by 2035 (CAGR 11.2%)", "Chewy/Amazon steady demand"],
    compliance: {
      us: ["FCC ID (WiFi)", "FDA food-contact hopper"],
      eu: ["CE-RED", "GDPR-compliant app + EU data hosting", "GPSR responsible person"],
      difficulty: "medium",
      note: "The app is half the product — demand white-label app with EN/DE/FR localization."
    },
    tariffUS: 0.33,
    freightUnit: 2.5,
    freightMode: "Sea freight · bulky box",
    season: "Year-round; holiday-travel spikes (Nov–Dec, summer)",
    orderBy: "Any month",
    risks: "App abandonment by the OEM bricks the product — contract app maintenance terms up front.",
    whyHot: "Higher AOV than fountains with the same pet-economy tailwind.",
    buyerTip: "2.4GHz-only WiFi chips cause most 1-star setup reviews — pay for dual-band."
  },
  {
    id: "litter-box",
    name: "Self-Cleaning Smart Litter Box",
    emoji: "🚽",
    track: "Smart Pet",
    tier: "profit",
    price1688: [60, 95],
    priceAlibaba: [80, 130],
    retailPrice: [250, 500],
    cnKeyword: "智能猫砂盆 自动",
    trendQuery: "self cleaning litter box",
    moq: 50,
    trendScore: 84,
    lifecycle: "early",
    chinaSignal: "90%+ of Petkit's revenue comes from smart litter boxes/feeders/fountains — the category is proven in China and still premium-priced in the West.",
    signals: ["High-ticket, low return rate", "Western incumbents price at $400–700 leaving a wide gap"],
    compliance: {
      us: ["FCC", "UL component report recommended"],
      eu: ["CE (LVD/EMC/Machinery safety)", "GPSR responsible person"],
      difficulty: "medium",
      note: "Pinch-protection sensor documentation is a must — past recalls in this category."
    },
    tariffUS: 0.33,
    freightUnit: 8,
    freightMode: "Sea freight only · palletize",
    season: "Year-round",
    orderBy: "Any month",
    risks: "Cheap vertical-wheel and swing-scoop designs killed cats in 2024–25 (a $3M lawsuit followed; PETA called for boycotts). Only the horizontal-drum architecture has a 20-year clean safety record — never source the vertical/scoop formats.",
    whyHot: "The highest-AOV pick in the strongest pet track; a $90 unit retails $250+ — and the safety scare is a filter you can pass while cheap competitors can't.",
    buyerTip: "Horizontal drum + redundant sensors (weight + IR + anti-pinch reversal) + OTA firmware only. Put the safety mechanism front-and-center in the listing — it converts."
  },
  {
    id: "robot-pet",
    name: "Emotional Companion Robot Pet",
    emoji: "🤖",
    track: "AI Toys",
    tier: "profit",
    price1688: [35, 60],
    priceAlibaba: [45, 80],
    retailPrice: [120, 250],
    cnKeyword: "情感陪伴机器人 宠物",
    trendQuery: "robot pet companion",
    moq: 100,
    trendScore: 90,
    lifecycle: "early",
    chinaSignal: "Ropet went viral at CES 2025 and raised $200k+ on Kickstarter; Chongker's lifelike AI cats target elderly + gift markets.",
    signals: ["Adult/elderly companionship angle avoids kids-privacy rules", "Crowdfunding-validated demand"],
    compliance: {
      us: ["FCC", "UN38.3 (battery)"],
      eu: ["CE-RED", "GPSR responsible person"],
      difficulty: "medium",
      note: "Marketing to adults (not children) keeps you out of COPPA/EN71 territory — position accordingly."
    },
    tariffUS: 0.33,
    freightUnit: 2,
    freightMode: "Air OK with battery docs",
    season: "Q4 + Valentine's/Mother's Day gifting",
    orderBy: "September for Q4",
    risks: "Novelty-return risk if interaction depth disappoints — test the AI in English yourself. Keep positioning strictly adult/elderly: kids-marketed AI toys drew Senate letters, an FTC-probe push, and a House committee inquiry into Chinese AI toys in 2025–26.",
    whyHot: "High AOV in the hardest-data new track of 2026, before Western brands consolidate it.",
    buyerTip: "Fur/fabric variants need flammability docs; verify English voice quality yourself before the PO."
  },
  {
    id: "solar-storage",
    name: "Balcony Solar Storage Accessories (EU)",
    emoji: "☀️",
    track: "Balcony Solar (EU)",
    tier: "profit",
    price1688: [8, 20],
    priceAlibaba: [12, 28],
    retailPrice: [40, 90],
    cnKeyword: "阳台光伏 储能 配件",
    trendQuery: "balkonkraftwerk speicher",
    moq: 200,
    trendScore: 74,
    lifecycle: "saturated",
    chinaSignal: "Germany's 1.3M installed balcony systems are now a replacement/upgrade market: new balcony-PV installs fell 6% in Q1 2026, but storage attach grew +67% — the growth moved from panels to batteries and their accessories.",
    signals: ["DE storage additions +67% (Q1 2026, 2GWh)", "New balcony-PV installs -6%; residential PV -21%", "Subsidy cuts in multiple cities; module prices +10–20% as China export rebates end"],
    compliance: {
      us: [],
      eu: ["CE (structural/load documentation)", "GPSR responsible person", "EU Forced Labour Regulation lands 2027 — demand polysilicon/aluminium provenance docs"],
      difficulty: "medium",
      note: "UFLPA/forced-labour rules put solar at the top of enforcement lists: panels and battery cells are red-zone; aluminium mounts and copper cables joined the 2025 high-priority list. Source with provenance paperwork or stick to plastic/structural small parts."
    },
    tariffUS: 0.33,
    freightUnit: 2,
    freightMode: "Sea freight · EU-only play",
    season: "EU install season Mar–Sep",
    orderBy: "January",
    risks: "The panel-kit gold rush is over (installs falling, subsidies cut). The defensible slice is storage-adjacent accessories — cabling, monitoring, brackets with documented material provenance. US buyers: plug-in balcony solar is legal in only a few states (Utah HB 340); look for UL 3700.",
    whyHot: "A 1.3M-unit installed base still needs accessories even as new installs cool — but this is now a value play, not a growth play.",
    buyerTip: "Sell into the upgrade cycle (storage retrofit kits, monitoring plugs), not new installs. Refuse suppliers who can't document aluminium/copper origin."
  },
  {
    id: "smart-plug",
    name: "Energy-Metering Smart Plug (Schuko)",
    emoji: "🔌",
    track: "Balcony Solar (EU)",
    tier: "profit",
    price1688: [3.5, 6],
    priceAlibaba: [5, 9],
    retailPrice: [20, 35],
    cnKeyword: "计量插座 WiFi 16A",
    trendQuery: "energy monitoring smart plug",
    moq: 500,
    trendScore: 82,
    lifecycle: "growth",
    chinaSignal: "Standard hardware in China's mature IoT supply chain; EU demand pulled up by balcony-solar owners wanting to see feed-in yields.",
    signals: ["Attach-rate product to 1.3M German solar systems", "Energy-price anxiety keeps EU demand structural"],
    compliance: {
      us: [],
      eu: ["CE-RED", "16A rating certification", "GDPR app note", "GPSR responsible person"],
      difficulty: "medium",
      note: "Schuko (Type F) plug format targets DE/NL/ES — don't ship US pins to Europe."
    },
    tariffUS: 0.33,
    freightUnit: 0.3,
    freightMode: "Sea · featherweight",
    season: "Year-round; spring spike with install season",
    orderBy: "February",
    risks: "Cheap relays fail at sustained 16A — this is the burn-hazard recall category; demand cycle-test reports.",
    whyHot: "Cheap to ship, high attach rate, and German buyers pay for measurement accuracy.",
    buyerTip: "Matter/Home-Assistant compatibility is the differentiator German forums actually discuss."
  },

  // ── TRAFFIC TIER ────────────────────────────────────────────
  {
    id: "spin-scrubber",
    name: "Cordless Electric Spin Scrubber",
    emoji: "🧽",
    track: "Home Cleaning",
    tier: "traffic",
    price1688: [6, 11],
    priceAlibaba: [8, 15],
    retailPrice: [30, 50],
    cnKeyword: "电动清洁刷 无线 长柄",
    trendQuery: "electric spin scrubber",
    moq: 300,
    trendScore: 91,
    lifecycle: "growth",
    chinaSignal: "Domestic Douyin cleaning-content wave preceded CleanTok; supply chain iterated to multi-head extendable designs before Western listings caught up.",
    signals: ["CleanTok before/after content is conversion gold", "Shark steam mop +5800% and Yass Clean 500k orders prove the UK cleaning wave"],
    compliance: {
      us: ["FCC", "UN38.3 + MSDS"],
      eu: ["CE/RoHS", "GPSR responsible person"],
      difficulty: "low",
      note: "IPX5+ waterproofing report matters — it lives in showers."
    },
    tariffUS: 0.33,
    freightUnit: 1.2,
    freightMode: "Sea for margin · air OK with battery docs",
    season: "Jan (new-year cleaning) + Q4 double peak",
    orderBy: "October for Jan peak",
    risks: "Torque fade after 3 months is the review killer — verify motor spec, not just RPM claims.",
    whyHot: "The most demo-able product in the hottest content niche (CleanTok).",
    buyerTip: "Extendable handle + 4 heads minimum; pastel colorways outperform."
  },
  {
    id: "carpet-cleaner",
    name: "Portable Carpet & Upholstery Cleaner",
    emoji: "🛋️",
    track: "Home Cleaning",
    tier: "traffic",
    price1688: [28, 45],
    priceAlibaba: [38, 60],
    retailPrice: [100, 160],
    cnKeyword: "布艺清洗机 手持 喷抽",
    trendQuery: "portable carpet cleaner",
    moq: 100,
    trendScore: 88,
    lifecycle: "growth",
    chinaSignal: "White-label spot-cleaner supply chain scaled after Bissell Little Green went CleanTok-viral; Chinese factories now offer stronger suction at half the price.",
    signals: ["Bissell Little Green is a permanent Movers & Shakers fixture", "Pet-owner overlap doubles the audience"],
    compliance: {
      us: ["UL/ETL strongly recommended (US retail requires it)", "FCC"],
      eu: ["CE (LVD/EMC)", "GPSR responsible person"],
      difficulty: "medium",
      note: "Corded design avoids battery paperwork entirely."
    },
    tariffUS: 0.33,
    freightUnit: 4,
    freightMode: "Sea freight · bulky",
    season: "Year-round; spring-cleaning + holiday spill season",
    orderBy: "Any month",
    risks: "Suction claims vs reality gap drives returns — test water-lift numbers on samples.",
    whyHot: "A $38 unit retailing at $120+ in a proven, still-underserved 'Bissell-alternative' slot.",
    buyerTip: "Include pet-mess attachment + enzyme cleaner sample — the bundle wins the listing."
  },
  {
    id: "flip-straw-bottle",
    name: "Flip-Straw Dual-Lid Water Bottle",
    emoji: "🥤",
    track: "Drinkware",
    tier: "traffic",
    price1688: [2.5, 4.5],
    priceAlibaba: [3.5, 6.5],
    retailPrice: [22, 40],
    cnKeyword: "弹跳吸管保温杯 两用",
    trendQuery: "flip straw water bottle",
    moq: 500,
    trendScore: 86,
    lifecycle: "growth",
    chinaSignal: "The Zhejiang drinkware cluster that built the Stanley wave has already retooled for flip-straw dual-lid formats as Western social feeds rotate.",
    signals: ["Stanley quencher trend declared dead (searches peaked Nov 2025)", "Owala FreeSip has taken over TikTok/Instagram", "Water-bottle category still grew +21% — the product died, the category didn't"],
    compliance: {
      us: ["FDA food contact", "Prop 65 lead-free seal documentation"],
      eu: ["LFGB (Germany)", "GPSR responsible person"],
      difficulty: "low",
      note: "Design your own bottle silhouette — do not copy Owala's protected trade dress."
    },
    tariffUS: 0.33,
    freightUnit: 1.0,
    freightMode: "Sea freight · dense and durable",
    season: "Year-round; Jan hydration + back-to-school peaks",
    orderBy: "Any month",
    risks: "Riding a successor trend means timing risk both ways — differentiate on silhouette and colorway drops, never clone the incumbent's look (trade-dress exposure).",
    whyHot: "The proven drinkware margin machine, pointed at the format that replaced the dead quencher trend.",
    buyerTip: "Leak-proof flip-lock is the review battleground; 24–32oz with a carry loop is the sweet spot."
  },
  {
    id: "heatless-curler",
    name: "Heatless Curling Set",
    emoji: "💇",
    track: "Hair Tools",
    tier: "traffic",
    price1688: [0.8, 2],
    priceAlibaba: [1.5, 3],
    retailPrice: [12, 25],
    cnKeyword: "无热卷发棒 睡眠卷发",
    trendQuery: "heatless curls",
    moq: 500,
    trendScore: 78,
    lifecycle: "saturated",
    chinaSignal: "Douyin overnight-curl content preceded the Western #heatlesscurls wave; satin supply chain makes variants trivially cheap.",
    signals: ["Hair tools hold 7 of top-10 consistent TikTok Shop UK best-sellers", "No-heat-damage narrative rides clean-beauty trend"],
    compliance: {
      us: [],
      eu: ["GPSR responsible person", "OEKO-TEX on satin is a selling point"],
      difficulty: "low",
      note: "Essentially zero certification burden — fastest possible market entry."
    },
    tariffUS: 0.38,
    freightUnit: 0.25,
    freightMode: "Air-friendly · featherweight",
    season: "Year-round; Q4 stocking-stuffer spike",
    orderBy: "Any month",
    risks: "Ad-competition is far past the saturation threshold — treat as a cash-cow: ride organic content, keep zero ad budget, no new SKU investment.",
    whyHot: "8–12× spread on a featherweight no-cert product — best cash-flow starter SKU on this list.",
    buyerTip: "Satin > silk-claims: test colorfastness; dark satin bleeding onto pillowcases is the 1-star pattern."
  },
  {
    id: "hair-dryer",
    name: "High-Speed Ionic Hair Dryer",
    emoji: "💨",
    track: "Hair Tools",
    tier: "traffic",
    price1688: [12, 22],
    priceAlibaba: [16, 30],
    retailPrice: [60, 150],
    cnKeyword: "高速吹风机 负离子",
    trendQuery: "high speed hair dryer",
    moq: 200,
    trendScore: 86,
    lifecycle: "growth",
    chinaSignal: "Post-Dyson patent-workaround generation matured in China's domestic market; 110k-rpm motors now ship white-label under $25.",
    signals: ["Dyson-alternative searches compound yearly", "TikTok hair-tool content is evergreen"],
    compliance: {
      us: ["UL/ETL mandatory (immersion-protection plug)", "FCC"],
      eu: ["CE (LVD/EMC)", "UK plug variant for TikTok Shop UK", "GPSR responsible person"],
      difficulty: "medium",
      note: "US hair dryers legally require immersion-protection (ALCI) plugs — many factory quotes omit this."
    },
    tariffUS: 0.33,
    freightUnit: 1.5,
    freightMode: "Sea for margin",
    season: "Q4 gifting + year-round base",
    orderBy: "August for Q4",
    risks: "Motor noise >60dB and burnt-smell QC failures dominate bad reviews — third-party inspection every batch ($200–350/day, worth it).",
    whyHot: "The 'Dyson look for $79' slot keeps minting mid-size brands.",
    buyerTip: "Magnetic attachments + display screen justify the premium band; verify real motor RPM."
  },
  {
    id: "massage-gun",
    name: "Mini Massage Gun (Type-C)",
    emoji: "💆",
    track: "Recovery & Wellness",
    tier: "traffic",
    price1688: [4.9, 6.9],
    priceAlibaba: [8, 12],
    retailPrice: [30, 100],
    cnKeyword: "筋膜枪 迷你",
    trendQuery: "mini massage gun",
    moq: 100,
    trendScore: 84,
    lifecycle: "saturated",
    chinaSignal: "Fully commoditized in China ($4.90 at 100 MOQ) — the arbitrage is mature but the spread is still 5–15×.",
    signals: ["Massage-gun market $1.5B → $3.7B by 2035", "Corporate-gifting channel underexploited"],
    compliance: {
      us: ["FCC", "UN38.3 + MSDS"],
      eu: ["CE/RoHS", "GPSR responsible person"],
      difficulty: "low",
      note: "Avoid medical claims; 'muscle recovery' phrasing keeps it a wellness product."
    },
    tariffUS: 0.33,
    freightUnit: 0.8,
    freightMode: "Air OK with battery docs",
    season: "Nov–Jan (gifting + resolutions)",
    orderBy: "September",
    risks: "Saturated on Amazon — viable via TikTok Shop bundles, gift boxes, or B2B corporate gifting, not solo listings.",
    whyHot: "Still the clearest demo of the factory-to-retail spread; a reliable volume filler.",
    buyerTip: "≤45dB noise + 4 heads + branded case; sell the gift box, not the gun."
  },
  {
    id: "leg-boots",
    name: "Air-Compression Leg Recovery Boots",
    emoji: "🦵",
    track: "Recovery & Wellness",
    tier: "traffic",
    price1688: [25, 45],
    priceAlibaba: [35, 60],
    retailPrice: [120, 250],
    cnKeyword: "气压腿部按摩 恢复靴",
    trendQuery: "leg compression boots",
    moq: 100,
    trendScore: 83,
    lifecycle: "early",
    chinaSignal: "Normatec-style compression hardware white-labeled in China at 1/6 the incumbent's price; runner/gym-recovery content is just starting in the West.",
    signals: ["'Longevity' movement upgraded wellness spend", "Incumbent anchors $800+ price perception"],
    compliance: {
      us: ["FDA general-wellness positioning", "FCC"],
      eu: ["CE", "GPSR responsible person"],
      difficulty: "medium",
      note: "Same claims discipline as LED masks — recovery, not therapy."
    },
    tariffUS: 0.33,
    freightUnit: 2.2,
    freightMode: "Sea for margin",
    season: "Jan fitness + marathon seasons (spring/fall)",
    orderBy: "October",
    risks: "Sizing/fit returns — offer XL calf option; pressure-accuracy QC matters.",
    whyHot: "Early-window pick in the longevity narrative with a huge incumbent price umbrella.",
    buyerTip: "Marathon-training Facebook groups and run clubs are the underpriced ad channel."
  },
  {
    id: "solar-camp-lights",
    name: "Solar Camping String Lights & Lantern",
    emoji: "🏕️",
    track: "Outdoor & Camping",
    tier: "traffic",
    price1688: [2.5, 6],
    priceAlibaba: [4, 9],
    retailPrice: [20, 40],
    cnKeyword: "太阳能露营灯 灯串",
    trendQuery: "solar camping lights",
    moq: 500,
    trendScore: 85,
    lifecycle: "growth",
    chinaSignal: "China is the global manufacturing hub for camping gear; solar-lighting demand up 62% while generic camp gear commoditizes.",
    signals: ["Camping equipment $27.8B → $47.4B by 2033", "Glamping-aesthetic content keeps compounding"],
    compliance: {
      us: ["FCC (if any wireless)"],
      eu: ["CE/RoHS", "IP65 report", "GPSR responsible person"],
      difficulty: "low",
      note: "LiFePO4 variants ease battery shipping restrictions."
    },
    tariffUS: 0.33,
    freightUnit: 0.5,
    freightMode: "Sea · light and packable",
    season: "Hard seasonal Mar–Aug",
    orderBy: "February — do not overbuy for fall",
    risks: "Seasonal stranding: unsold September inventory sits until March.",
    whyHot: "The fastest-growing niche (+62%) inside a steady $28B category.",
    buyerTip: "Retractable/spool designs photograph better and cut returns from tangle complaints."
  },
  {
    id: "moon-chair",
    name: "Ultralight Camping Moon Chair",
    emoji: "🪑",
    track: "Outdoor & Camping",
    tier: "traffic",
    price1688: [9, 16],
    priceAlibaba: [12, 22],
    retailPrice: [40, 70],
    cnKeyword: "月亮椅 超轻 铝合金",
    trendQuery: "camping moon chair",
    moq: 300,
    trendScore: 82,
    lifecycle: "growth",
    chinaSignal: "Precision-aluminum camp furniture supply chain (Helinox-style) concentrated in China; domestic glamping wave drove design iteration.",
    signals: ["Households buy 2–4 at once", "Instagram-visual product with organic reach"],
    compliance: {
      us: [],
      eu: ["CE general safety", "REACH (fabric coatings)", "GPSR responsible person"],
      difficulty: "low",
      note: "Load-rating documentation is the one paper that matters."
    },
    tariffUS: 0.33,
    freightUnit: 2.5,
    freightMode: "Sea freight · compact carry bag",
    season: "Mar–Sep",
    orderBy: "December–January",
    risks: "Claimed 330lb ratings often fail real tests — break one yourself before the PO.",
    whyHot: "Multi-unit purchases lift AOV in a proven, visual category.",
    buyerTip: "7075 aluminum + ≤4.4lb packed + ≥330lb verified: hit all three or reviews will find you."
  },
  {
    id: "blender-bottle",
    name: "Portable Blender Bottle (USB-C)",
    emoji: "🧃",
    track: "Kitchen",
    tier: "traffic",
    price1688: [3.2, 6],
    priceAlibaba: [4.5, 8.5],
    retailPrice: [20, 35],
    cnKeyword: "便携榨汁杯 无线",
    trendQuery: "portable blender",
    moq: 500,
    trendScore: 90,
    lifecycle: "growth",
    chinaSignal: "Chinese domestic juicer-cup wave preceded the West by two seasons; Ninja Blast's +1800% UK order spike validates the Western demand curve.",
    signals: ["Ninja Blast orders +1800% (TikTok Shop UK, Mar–May 2025)", "Fitness + office + gifting triple demand"],
    compliance: {
      us: ["FDA food contact", "FCC", "UN38.3 + MSDS"],
      eu: ["CE/RoHS", "LFGB for Germany", "GPSR responsible person"],
      difficulty: "low",
      note: "Blade-lock safety interlock documentation prevents the obvious liability."
    },
    tariffUS: 0.33,
    freightUnit: 0.9,
    freightMode: "Air OK with battery docs",
    season: "Jan resolutions + May summer prep",
    orderBy: "November for Jan",
    risks: "Weak motors that stall on frozen fruit are the #1 refund driver — spec ≥1500mAh and test with ice.",
    whyHot: "A branded competitor just proved +1800% demand; white-label follows the wake.",
    buyerTip: "Pastel colorways outsell dark 3:1; sell the 'gym + office' two-bottle bundle."
  },
  {
    id: "veg-chopper",
    name: "14-in-1 Vegetable Chopper",
    emoji: "🥕",
    track: "Kitchen",
    tier: "traffic",
    price1688: [1.8, 4],
    priceAlibaba: [2.8, 5.5],
    retailPrice: [25, 35],
    cnKeyword: "多功能切菜器 切丁",
    trendQuery: "vegetable chopper",
    moq: 1000,
    trendScore: 80,
    lifecycle: "saturated",
    chinaSignal: "Fully mature Yiwu-ecosystem product; differentiation now happens on blade steel and accessory count, not concept.",
    signals: ["Amazon kitchen evergreen", "Live-commerce impulse price point"],
    compliance: {
      us: ["FDA food contact"],
      eu: ["LFGB (unlocks Germany)", "GPSR responsible person"],
      difficulty: "low",
      note: "LFGB test (~$500) filters out most lazy competitors in the German market."
    },
    tariffUS: 0.33,
    freightUnit: 0.6,
    freightMode: "Sea · nests well, low cube",
    season: "Nov–Dec holiday cooking + Jan",
    orderBy: "September",
    risks: "Race-to-bottom pricing on Amazon US — the margin lives in EU marketplaces and bundles.",
    whyHot: "Reliable traffic SKU: cheap, demo-able, high review velocity.",
    buyerTip: "420 blade steel vs 301 decides your review score; include finger guard."
  },
  {
    id: "cable-powerbank",
    name: "Built-in-Cable Mini Power Bank",
    emoji: "🔋",
    track: "Phone & Charging",
    tier: "traffic",
    price1688: [4, 8],
    priceAlibaba: [6, 11],
    retailPrice: [26, 50],
    cnKeyword: "自带线充电宝 迷你",
    trendQuery: "power bank built in cable",
    moq: 500,
    trendScore: 88,
    lifecycle: "growth",
    chinaSignal: "Anker's built-in-cable design spawned an entire white-label generation; Chinese domestic market already moved to display-screen variants.",
    signals: ["Top-selling China-sourced electronics format on Amazon 2025", "Travel-content virality"],
    compliance: {
      us: ["FCC", "UN38.3 + MSDS mandatory", "UL 2056 strongly advised"],
      eu: ["CE/RoHS", "GPSR responsible person"],
      difficulty: "high",
      note: "Power banks are the #1 CPSC recall category (fire) — 66% of 2025 recalls involved Chinese products, heavily this category. Cell quality is everything."
    },
    tariffUS: 0.33,
    freightUnit: 0.5,
    freightMode: "Sea preferred; air needs full battery dossier",
    season: "Year-round; travel-season spikes",
    orderBy: "Any month",
    risks: "Recall/fire liability: only buy A-grade cells (ATL/BYD/Lishen) with traceable reports; product-liability insurance is not optional.",
    whyHot: "Format-level differentiation in an evergreen category — the display-screen variant is still early in the West.",
    buyerTip: "The extra $0.80/unit for branded cells is the cheapest insurance you'll ever buy."
  },
  {
    id: "cosmetic-organizer",
    name: "Rotating Clear Cosmetics Organizer",
    emoji: "💄",
    track: "Home Storage",
    tier: "traffic",
    price1688: [2, 4.5],
    priceAlibaba: [3, 6],
    retailPrice: [18, 35],
    cnKeyword: "化妆品收纳盒 旋转 亚克力",
    trendQuery: "makeup organizer",
    moq: 500,
    trendScore: 78,
    lifecycle: "saturated",
    chinaSignal: "Beauty tools + organization = 66% of Temu's top-seller structure (37% + 29%) — the two categories this product straddles.",
    signals: ["Temu Q1 2025: organizers = 29% of top items", "Vanity-tour content keeps demand alive"],
    compliance: {
      us: [],
      eu: ["GPSR responsible person"],
      difficulty: "low",
      note: "Zero-cert product; packaging quality is the differentiator."
    },
    tariffUS: 0.33,
    freightUnit: 1,
    freightMode: "Sea · fragile, double-box",
    season: "Jan organizing + Q4 gifting",
    orderBy: "October",
    risks: "Acrylic cracks in transit — drop-test packaging or eat 10% breakage returns.",
    whyHot: "Cheap traffic SKU that cross-sells into beauty-device listings.",
    buyerTip: "360° rotating + adjustable trays is the winning spec set; film unboxing-quality packaging."
  },

  // ── IDENTITY TIER ───────────────────────────────────────────
  {
    id: "mamian-skirt",
    name: "Modern Mamian (Horse-Face) Skirt",
    emoji: "👘",
    track: "New Chinese Style",
    tier: "identity",
    price1688: [6, 12],
    priceAlibaba: [10, 18],
    retailPrice: [20, 60],
    cnKeyword: "马面裙 日常 通勤",
    trendQuery: "mamian skirt",
    moq: 100,
    trendScore: 92,
    lifecycle: "growth",
    chinaSignal: "Caoxian's hanfu cluster sold ¥13B in 2025 with overseas mamian orders up ~10x year-over-year across 32 countries — the 2024 peak wasn't the peak.",
    signals: ["#hanfu: 1.6B+ TikTok views", "Diaspora + fashion-forward Western buyers", "Weddings/graduation/cultural events drive year-round demand"],
    compliance: {
      us: ["FTC fiber-content labeling"],
      eu: ["Textile labeling regulation", "OEKO-TEX as selling point", "GPSR responsible person"],
      difficulty: "low",
      note: "Textiles are the lowest-compliance category on this list."
    },
    tariffUS: 0.4,
    freightUnit: 0.6,
    freightMode: "Air or sea · high value density",
    season: "No seasonality (rare!) — Lunar New Year + wedding spikes",
    orderBy: "Any month",
    risks: "Quality tiers vary wildly — jacquard weave density and pleat count define the product; cheap prints damage the story.",
    whyHot: "A story-rich product Western fast fashion can't copy credibly, with zero white-label red ocean.",
    buyerTip: "Office-friendly lengths + elastic waistband variants move fastest overseas; source from Caoxian/Hangzhou clusters."
  },
  {
    id: "panku-shirt",
    name: "New-Chinese Frog-Button Shirt",
    emoji: "🀄",
    track: "New Chinese Style",
    tier: "identity",
    price1688: [5, 11],
    priceAlibaba: [8, 16],
    retailPrice: [30, 70],
    cnKeyword: "新中式 盘扣衬衫",
    trendQuery: "chinese style shirt",
    moq: 100,
    trendScore: 79,
    lifecycle: "early",
    chinaSignal: "New-Chinese-style apparel grew +120% domestically Jan–Apr 2025; the daily-wear (not costume) cut is what exports.",
    signals: ["Quiet-luxury aesthetic overlap", "Museum-collab visual language photographs organically"],
    compliance: {
      us: ["FTC fiber labeling"],
      eu: ["Textile labeling", "GPSR responsible person"],
      difficulty: "low",
      note: "Sell the craft story (frog buttons, jacquard) — that's the moat against Shein knockoffs."
    },
    tariffUS: 0.4,
    freightUnit: 0.5,
    freightMode: "Air or sea",
    season: "Year-round; Lunar New Year spike",
    orderBy: "Any month",
    risks: "Domestic 'guochao' logo-print hype is cooling — stock the wearable daily pieces, not costume items.",
    whyHot: "Earliest window of the identity tier: real growth data, near-zero Western competition.",
    buyerTip: "Linen-cotton blends for Western sizing; offer a size chart in inches — most factories won't."
  },
  {
    id: "tea-set",
    name: "Travel Gongfu Tea Set",
    emoji: "🍵",
    track: "Tea Culture",
    tier: "identity",
    price1688: [5, 12],
    priceAlibaba: [8, 18],
    retailPrice: [35, 80],
    cnKeyword: "旅行茶具 快客杯 套装",
    trendQuery: "gongfu tea set",
    moq: 200,
    trendScore: 81,
    lifecycle: "early",
    chinaSignal: "#ChineseTea content passed 200M views; OG Tea sold tens of thousands of boxes in the US within a year via Chinese-style livestreams; Chagee entered the US in 2025.",
    signals: ["Tea-ceremony content is the calm-aesthetic niche of 2026", "Gift-box conversion strong", "China exported $1.74B of tea in 2023"],
    compliance: {
      us: ["FDA food contact (ceramic lead/cadmium limits!)"],
      eu: ["EU 84/500/EEC ceramic migration limits", "LFGB for Germany", "GPSR responsible person"],
      difficulty: "medium",
      note: "Ceramic lead/cadmium migration tests are non-negotiable — glaze failures are an import-refusal classic."
    },
    tariffUS: 0.33,
    freightUnit: 1.2,
    freightMode: "Sea · fragile, foam-mold packaging",
    season: "Q4 gifting dominant; year-round content sales",
    orderBy: "August for Q4",
    risks: "Breakage in transit — insist on molded-foam packaging and drop-test certification of the shipping box.",
    whyHot: "Culture-story product with rising content tailwind and no white-label red ocean.",
    buyerTip: "Bundle a cold-brew oolong sampler — consumable attach turns a one-time gift into a repeat customer."
  },

  // ── WAVE 2 ADDITIONS (docs/research/08-tracks-wave2.md) ─────
  {
    id: "car-fridge",
    name: "Compressor Car Fridge (Dual-Zone)",
    emoji: "🧊",
    track: "Auto & Overlanding",
    tier: "profit",
    price1688: [62, 125],
    priceAlibaba: [85, 160],
    retailPrice: [199, 399],
    cnKeyword: "车载冰箱 压缩机 双温区",
    trendQuery: "car refrigerator",
    moq: 50,
    trendScore: 91,
    lifecycle: "early",
    chinaSignal: "Foshan/Zhongshan compressor-fridge cluster (Alpicool et al.) owns global supply; China's domestic road-trip wave matured the product a generation ahead of Western overlanding demand.",
    signals: ["Compressor car fridge market $1.07B → $6.78B by 2034 (CAGR 20.3%)", "Overlanding adoption +52%", "68% of outdoor users prefer compressor over thermoelectric"],
    compliance: {
      us: ["FCC", "DOE refrigerant/energy docs", "UL component report recommended"],
      eu: ["CE (LVD/EMC)", "F-gas refrigerant documentation", "GPSR responsible person"],
      difficulty: "medium",
      note: "Refrigerant type and compressor brand (LG/Secop vs no-name) decide both customs paperwork and review scores."
    },
    tariffUS: 0.33,
    freightUnit: 12,
    freightMode: "Sea freight only · fragile compressor handling",
    season: "Mar–Aug road-trip season",
    orderBy: "January",
    risks: "Freight damage and compressor DOA are the margin killers — drop-test packaging and per-batch inspection are non-negotiable at this AOV.",
    whyHot: "Fastest-growing track of the second wave: 20%+ CAGR, high ticket, and a structural (not viral) demand curve.",
    buyerTip: "15–35L dual-zone with detachable battery slot is the spec sweet spot; bundle a protective cover."
  },
  {
    id: "rollator",
    name: "Lightweight Four-Wheel Rollator",
    emoji: "🚶",
    track: "Silver Economy",
    tier: "profit",
    price1688: [25, 49],
    priceAlibaba: [35, 65],
    retailPrice: [89, 169],
    cnKeyword: "老年助行车 四轮 折叠",
    trendQuery: "rollator walker",
    moq: 100,
    trendScore: 84,
    lifecycle: "early",
    chinaSignal: "Hebei mobility-aid cluster supplies global medical distributors; direct-to-consumer e-commerce is still a fraction of the channel — the DTC arbitrage is early.",
    signals: ["Assistive-device market $34.7B (2025)", "1.1B people aged 60+, 1.5B by 2030", "Adult children buy as gifts — content-commerce friendly"],
    compliance: {
      us: ["FDA Class I (510(k)-exempt) — registration still required", "ASTM/ISO 11199 test report"],
      eu: ["EU MDR Class I self-declaration", "EN ISO 11199-2", "GPSR responsible person"],
      difficulty: "medium",
      note: "Class I exempt ≠ zero paperwork: importer FDA listing and load-test reports are required. Stay away from powered mobility (Class II)."
    },
    tariffUS: 0.33,
    freightUnit: 6,
    freightMode: "Sea freight · flat-packs well",
    season: "Year-round; Q4 gifting bump",
    orderBy: "Any month",
    risks: "Weight-capacity claims must be independently tested — mobility-aid failures injure vulnerable users and juries know it.",
    whyHot: "Demographics guarantee a decade of demand; competition is thin because the category isn't sexy.",
    buyerTip: "Under-6kg carbon-look frames photograph young — 'gift for mom' framing outsells 'medical device' framing 5:1."
  },
  {
    id: "pill-organizer",
    name: "Smart Reminder Pill Organizer",
    emoji: "💊",
    track: "Silver Economy",
    tier: "traffic",
    price1688: [3.5, 11],
    priceAlibaba: [5, 15],
    retailPrice: [25, 60],
    cnKeyword: "智能药盒 定时提醒",
    trendQuery: "smart pill organizer",
    moq: 300,
    trendScore: 80,
    lifecycle: "early",
    chinaSignal: "Shenzhen small-electronics cluster ships timer/alarm pill cases white-label; Western DTC brands mark up 5x with zero hardware differentiation.",
    signals: ["Elderly smart-device usage +41%", "Caregiver gifting demand", "FSA/HSA eligibility angle in the US"],
    compliance: {
      us: ["FCC (if BLE)", "not a medical device if it only reminds"],
      eu: ["CE/RoHS", "GPSR responsible person"],
      difficulty: "low",
      note: "Keep it a reminder gadget — dose-dispensing claims cross into medical-device territory."
    },
    tariffUS: 0.33,
    freightUnit: 0.4,
    freightMode: "Air-friendly · featherweight",
    season: "Year-round; Q4 + New Year health resolutions",
    orderBy: "Any month",
    risks: "App-dependent models churn — standalone alarm versions have fewer returns and no software liability.",
    whyHot: "Cheap, light, gift-friendly entry into the silver-economy track.",
    buyerTip: "Large-print weekday labels and a loud alarm beat app features for the actual end user."
  },
  {
    id: "walking-pad",
    name: "Foldable Walking Pad",
    emoji: "🏃",
    track: "Home Fitness",
    tier: "profit",
    price1688: [76, 111],
    priceAlibaba: [100, 150],
    retailPrice: [199, 299],
    cnKeyword: "走步机 可折叠 家用",
    trendQuery: "walking pad",
    moq: 50,
    trendScore: 88,
    lifecycle: "growth",
    chinaSignal: "KingSmith/WalkingPad built the category and China owns it outright — CES 2026 and IFA 2025 launches keep iterating (suitcase-fold formats).",
    signals: ["Walking-pad market ~$4.9B (2025), CAGR 7.6%", "\"walking pad under desk\" ~9,900 monthly searches, January peak", "Hybrid-work desk-fitness demand is structural"],
    compliance: {
      us: ["UL/ETL strongly advised", "FCC"],
      eu: ["CE (LVD/EMC/Machinery)", "GPSR responsible person"],
      difficulty: "medium",
      note: "Motor safety cutoff and belt pinch documentation matter; skip folding-handrail variants with hinge-failure histories."
    },
    tariffUS: 0.33,
    freightUnit: 15,
    freightMode: "Sea freight only · 25kg+ per unit",
    season: "Dec–Feb (New Year fitness), Sep (back to office)",
    orderBy: "October",
    risks: "Foldable-variant search interest peaked Feb 2025 then cooled — the head of Amazon is crowded; win on quietness (≤50dB), remote UX, and weight capacity honesty.",
    whyHot: "The one home-fitness category with structural (not resolution-spike) demand and an all-China supply chain.",
    buyerTip: "Verify real motor wattage and 265lb+ capacity yourself; freight class makes returns brutal — QC every batch."
  },
  {
    id: "bottle-warmer",
    name: "Portable USB-C Bottle Warmer",
    emoji: "🍼",
    track: "Baby Care",
    tier: "traffic",
    price1688: [6, 12.5],
    priceAlibaba: [9, 18],
    retailPrice: [39, 69],
    cnKeyword: "便携暖奶器 无线",
    trendQuery: "portable bottle warmer",
    moq: 200,
    trendScore: 85,
    lifecycle: "growth",
    chinaSignal: "Guangdong/Zhejiang baby-electronics cluster moved the category cordless a season before Western brands; battery-powered units are heading toward 60%+ of the mix.",
    signals: ["Bottle-warmer market $312M → $565M by 2035 (CAGR 6.8%)", "Portable/battery is the fastest-growing subsegment", "Registry + gifting demand"],
    compliance: {
      us: ["FDA food contact", "FCC", "UN38.3 + MSDS"],
      eu: ["CE/RoHS", "LFGB", "GPSR responsible person"],
      difficulty: "medium",
      note: "Baby category = zero tolerance: overheat cutoff documentation and temperature-accuracy tests are mandatory. Avoid WiFi baby monitors entirely (privacy politics)."
    },
    tariffUS: 0.33,
    freightUnit: 0.8,
    freightMode: "Air OK with battery docs",
    season: "Year-round; baby-shower season spring/summer",
    orderBy: "Any month",
    risks: "Temperature accuracy ±2°C is the review line; anything that overheats formula ends the brand — inspect every batch.",
    whyHot: "The fastest-growing baby subsegment without the regulatory minefield of monitors or toys.",
    buyerTip: "Sell the diaper-bag use case (car trips, night feeds); leather-look sleeve variants command premium."
  },
  {
    id: "pruning-set",
    name: "Cordless Pruning Shears + Mini Saw Set",
    emoji: "✂️",
    track: "Garden & DIY",
    tier: "traffic",
    price1688: [17, 36],
    priceAlibaba: [25, 50],
    retailPrice: [79, 159],
    cnKeyword: "电动修枝剪 迷你锯 套装",
    trendQuery: "electric pruning shears",
    moq: 200,
    trendScore: 82,
    lifecycle: "growth",
    chinaSignal: "Yongkang power-tool cluster standardized the 21V battery platform — shears, mini saw and blower can share packs, which the West sells separately.",
    signals: ["Cordless holds 65%+ of pruning-tool demand", "Aging Western gardeners need low-effort tools (silver-economy synergy)", "Spring + fall double season"],
    compliance: {
      us: ["FCC", "UN38.3 + MSDS", "UL 62841 advised"],
      eu: ["CE (Machinery + LVD)", "GPSR responsible person"],
      difficulty: "medium",
      note: "Blade-guard interlock documentation matters — finger injuries drive both returns and liability."
    },
    tariffUS: 0.33,
    freightUnit: 2,
    freightMode: "Sea for margin · air OK with battery docs",
    season: "Mar–May + Sep–Oct pruning seasons",
    orderBy: "December",
    risks: "Mini chainsaws are a $30–40 white-label bloodbath with battery-spec fraud rampant — the shared-battery SET is the differentiation, not the saw alone.",
    whyHot: "Set economics (one battery platform, three tools) lift AOV out of the single-tool price war.",
    buyerTip: "Test claimed amp-hours yourself; include two batteries — 'always one charging' is the review phrase that sells."
  },
  {
    id: "aroma-diffuser",
    name: "Smart Aroma Diffuser + Car Vent Clip",
    emoji: "🕯️",
    track: "Home Fragrance",
    tier: "traffic",
    price1688: [3, 17],
    priceAlibaba: [5, 25],
    retailPrice: [25, 129],
    cnKeyword: "香薰机 智能 车载香薰",
    trendQuery: "aroma diffuser",
    moq: 300,
    trendScore: 81,
    lifecycle: "growth",
    chinaSignal: "South-China ultrasonic and waterless-diffuser lines are fully mature; the hardware the West brands at $99+ ships white-label under $15.",
    signals: ["Fragrance-diffuser market $29.2B → +$1.6B in 2026 alone", "Home-fragrance CAGR 9.2% (wellness-at-home driver)", "Car-scent clip is the impulse add-on"],
    compliance: {
      us: ["FCC", "IFRA note if bundling oils"],
      eu: ["CE/RoHS", "CLP labeling if oils included", "GPSR responsible person"],
      difficulty: "low",
      note: "Sell hardware; if you bundle oils, the oil supplier's IFRA/CLP paperwork becomes your problem — vet it."
    },
    tariffUS: 0.33,
    freightUnit: 0.7,
    freightMode: "Air-friendly · light",
    season: "Q4 gifting + Jan wellness peaks",
    orderBy: "September",
    risks: "The consumable (oil) is where brands lock customers — hardware-only plays face subscription-brand competition; consider a private-label oil attach.",
    whyHot: "Wellness-at-home tailwind on featherweight logistics — a clean margin filler for gift-season carts.",
    buyerTip: "Waterless nebulizing units are the premium tier the market is upgrading to; timers and auto-off are table stakes."
  },
  {
    id: "vac-consumables",
    name: "Robot-Vacuum Compatible Consumables Kit",
    emoji: "🧹",
    track: "Home Cleaning",
    tier: "traffic",
    price1688: [0.7, 3.5],
    priceAlibaba: [1.5, 5],
    retailPrice: [15, 35],
    cnKeyword: "扫地机器人 配件 滤网 拖布",
    trendQuery: "robot vacuum replacement parts",
    moq: 500,
    trendScore: 83,
    lifecycle: "growth",
    chinaSignal: "Dreame/Roborock/Ecovacs won shelf space worldwide (Dreame is #1 in 30 countries) — every unit they sell creates a filters-mops-dustbags annuity the brands price at 5x.",
    signals: ["Chinese robot-vacuum brands lead 30+ national markets", "Consumables repurchase every 2–3 months", "Compatible-parts search volume compounds with the installed base"],
    compliance: {
      us: [],
      eu: ["GPSR responsible person"],
      difficulty: "low",
      note: "Compatibility claims are nominative fair use — name the model ('fits Roborock S8'), never use brand logos, and don't clone patented brush geometries."
    },
    tariffUS: 0.33,
    freightUnit: 0.3,
    freightMode: "Sea · light and dense",
    season: "Year-round; Jan cleaning spike",
    orderBy: "Any month",
    risks: "Model-cycle risk: a kit SKU dies when its target model does — spread across the 5 best-selling models and refresh the lineup yearly.",
    whyHot: "Pure repeat-purchase economics riding the Chinese-brand premium wave without competing against it.",
    buyerTip: "HEPA-grade filter claims need a test report; bundle per-model (filters + side brushes + mops + bags) — singles don't convert."
  },
];

const TRACKS = [
  "All Tracks",
  "Beauty Devices",
  "Smart Pet",
  "AI Toys",
  "Balcony Solar (EU)",
  "Home Cleaning",
  "Drinkware",
  "Hair Tools",
  "Recovery & Wellness",
  "Outdoor & Camping",
  "Kitchen",
  "Phone & Charging",
  "Home Storage",
  "New Chinese Style",
  "Tea Culture",
  "Auto & Overlanding",
  "Silver Economy",
  "Home Fitness",
  "Baby Care",
  "Garden & DIY",
  "Home Fragrance"
];

const TIER_LABELS = {
  profit: { label: "Profit pick", cls: "tier-profit" },
  traffic: { label: "Volume pick", cls: "tier-traffic" },
  identity: { label: "Signature pick", cls: "tier-identity" }
};

const LIFECYCLE_LABELS = {
  early: { label: "Early window", cls: "lc-early" },
  growth: { label: "Growth", cls: "lc-growth" },
  saturated: { label: "Saturated", cls: "lc-saturated" }
};
