// Curated China bestseller data for Western B2B buyers.
// All prices in USD. factoryPrice = EXW unit price range at typical MOQ.
// trendScore 0-100 (demand momentum), saturation: low | medium | high (competition risk).
const PRODUCTS = [
  {
    id: "p001",
    name: "Portable Blender Bottle (USB-C)",
    track: "Home & Kitchen",
    emoji: "🥤",
    factoryPrice: [3.2, 6.8],
    retailPrice: [19.99, 34.99],
    moq: 500,
    trendScore: 96,
    saturation: "medium",
    signals: ["TikTok US viral", "Amazon BSR Top 20", "High gifting demand"],
    certifications: ["FDA (food contact)", "FCC", "CE/RoHS"],
    logistics: "Small parcel · air-friendly · battery: needs UN38.3 + MSDS",
    seasonality: "Year-round, peaks Jan (resolutions) & May (summer prep)",
    whyHot: "One-tap demo makes perfect short-video content. Fitness + office crowds overlap, and gifting keeps Q4 strong.",
    buyerTip: "Insist on ≥1500mAh battery and food-grade PCTG. Pastel colorways outsell dark 3:1 in US/EU."
  },
  {
    id: "p002",
    name: "Solar Motion-Sensor Garden Lights (4-pack)",
    track: "Outdoor & Garden",
    emoji: "💡",
    factoryPrice: [2.1, 4.5],
    retailPrice: [25.99, 39.99],
    moq: 1000,
    trendScore: 92,
    saturation: "medium",
    signals: ["Amazon BSR Top 10 (Garden)", "Long EU summer season", "High repeat B2B orders"],
    certifications: ["CE/RoHS", "IP65 report", "UKCA for UK"],
    logistics: "Sea freight economics · no battery restrictions (LiFePO4 variants easier)",
    seasonality: "Mar–Sep peak in EU/US; buy inventory Dec–Feb",
    whyHot: "Wire-free install is the killer feature for Western homeowners. Solar angle rides the energy-saving narrative.",
    buyerTip: "≥100 LED beads and true IP65 separate 4.5-star listings from returns. Bundle 4-packs to lift AOV."
  },
  {
    id: "p003",
    name: "Mini Massage Gun (Type-C)",
    track: "Sports & Health",
    emoji: "💆",
    factoryPrice: [8.5, 16.0],
    retailPrice: [39.99, 79.99],
    moq: 300,
    trendScore: 90,
    saturation: "high",
    signals: ["Amazon evergreen", "Gym-culture staple", "Corporate gifting"],
    certifications: ["FCC", "CE/RoHS", "UN38.3 (battery)"],
    logistics: "Small parcel · air OK with battery docs",
    seasonality: "Peaks Nov–Jan (gifting + fitness resolutions)",
    whyHot: "Pocket size + USB-C solved the portability complaint of gen-1 guns. Strong gift-box conversion.",
    buyerTip: "Noise ≤45dB is the review battleground. Ship with 4 heads minimum; brand the carry case."
  },
  {
    id: "p004",
    name: "MagSafe Power Bank with Stand",
    track: "Consumer Electronics",
    emoji: "🔋",
    factoryPrice: [6.5, 12.0],
    retailPrice: [29.99, 49.99],
    moq: 500,
    trendScore: 95,
    saturation: "medium",
    signals: ["TikTok US viral", "iPhone ecosystem tailwind", "High ad ROAS"],
    certifications: ["FCC", "CE/RoHS", "UN38.3 + MSDS", "MFi optional"],
    logistics: "Small parcel · battery paperwork mandatory for air",
    seasonality: "Year-round; spikes with each iPhone launch (Sep–Oct)",
    whyHot: "Snap-on demo is natural short-video material. The built-in stand variant doubled conversion in 2025.",
    buyerTip: "10000mAh + kickstand is the sweet spot. Verify real magnet pull force (≥8N) — the #1 refund reason."
  },
  {
    id: "p005",
    name: "Pet Water Fountain (Wireless Pump)",
    track: "Pet Supplies",
    emoji: "🐱",
    factoryPrice: [5.5, 11.0],
    retailPrice: [29.99, 49.99],
    moq: 500,
    trendScore: 88,
    saturation: "low",
    signals: ["Pet economy growth", "Filter refill recurring revenue", "Chewy/Amazon demand"],
    certifications: ["FCC", "CE/RoHS", "FDA (food contact parts)"],
    logistics: "Mid-size parcel · sea freight for margin",
    seasonality: "Year-round stable; slight summer peak",
    whyHot: "Wireless-pump generation removed the cable-in-water cleaning pain. Filters create a subscription-like backend.",
    buyerTip: "Pump noise ≤30dB and 2L+ capacity are the review drivers. Private-label the filters — that's the real margin."
  },
  {
    id: "p006",
    name: "14-in-1 Vegetable Chopper",
    track: "Home & Kitchen",
    emoji: "🥕",
    factoryPrice: [2.8, 5.5],
    retailPrice: [24.99, 34.99],
    moq: 1000,
    trendScore: 91,
    saturation: "high",
    signals: ["TikTok Shop top seller", "Live-commerce classic", "Impulse price point"],
    certifications: ["FDA (food contact)", "LFGB for EU/Germany"],
    logistics: "Sea freight · nests well, low cube cost",
    seasonality: "Peaks Nov–Dec (holiday cooking) and Jan",
    whyHot: "Satisfying demo content converts on sight. Low price = instant decision, huge volume plays.",
    buyerTip: "Blade steel (420 vs 301) decides reviews. Include finger guard + cleaning tool; LFGB unlocks Germany."
  },
  {
    id: "p007",
    name: "New-Chinese-Style Embroidered Hoodie",
    track: "Apparel & Accessories",
    emoji: "🦁",
    factoryPrice: [9.0, 18.0],
    retailPrice: [49.99, 89.99],
    moq: 300,
    trendScore: 84,
    saturation: "low",
    signals: ["Guochao aesthetic crossing over", "Streetwear niche on TikTok", "High share rate"],
    certifications: ["OEKO-TEX preferred", "CPSIA if youth sizes"],
    logistics: "Sea freight · flat-pack, low cube",
    seasonality: "Aug–Feb (fall/winter + Lunar New Year story)",
    whyHot: "Lion-dance and calligraphy motifs photograph brilliantly — organic social reach without ad spend.",
    buyerTip: "Heavyweight fleece (≥380gsm) and real embroidery (not print) justify the premium price band."
  },
  {
    id: "p008",
    name: "Bladeless Neck Fan",
    track: "Consumer Electronics",
    emoji: "🌀",
    factoryPrice: [3.5, 8.0],
    retailPrice: [19.99, 39.99],
    moq: 500,
    trendScore: 89,
    saturation: "medium",
    signals: ["Summer surge product", "Theme-park/commute use case", "TikTok demo-friendly"],
    certifications: ["FCC", "CE/RoHS", "UN38.3 (battery)"],
    logistics: "Small parcel · air with battery docs",
    seasonality: "Hard seasonal: Apr–Aug. Order by Feb.",
    whyHot: "Hands-free cooling with a wearable form factor; bladeless design killed the hair-safety objection.",
    buyerTip: "≥8h battery on low is the spec that sells. Stock out by July — don't overbuy for fall."
  },
  {
    id: "p009",
    name: "Hyaluronic Acid Ampoule Serum (30-pack)",
    track: "Beauty & Personal Care",
    emoji: "💧",
    factoryPrice: [4.5, 9.0],
    retailPrice: [24.99, 45.99],
    moq: 1000,
    trendScore: 93,
    saturation: "medium",
    signals: ["Ingredient-led content trend", "C-beauty credibility rising", "High repeat purchase"],
    certifications: ["FDA cosmetic listing (US)", "EU CPNP + Responsible Person", "MoCRA compliance"],
    logistics: "Small parcel · liquids: check carrier rules",
    seasonality: "Year-round; winter dryness peak",
    whyHot: "Single-dose format reads as hygienic + travel-friendly; ingredient storytelling drives creator content.",
    buyerTip: "Compliance is the moat: EU CPNP registration filters out 90% of lazy competitors. Verify INCI lists early."
  },
  {
    id: "p010",
    name: "Collapsible Storage Crates w/ Wheels",
    track: "Home & Kitchen",
    emoji: "📦",
    factoryPrice: [4.0, 9.5],
    retailPrice: [27.99, 49.99],
    moq: 500,
    trendScore: 83,
    saturation: "medium",
    signals: ["Moving-season demand", "RV/camping crossover", "Costco-style multipacks"],
    certifications: ["CE (general product safety)"],
    logistics: "Sea freight only · folds flat, excellent cube efficiency",
    seasonality: "May–Sep (moving) + Dec–Jan (organizing)",
    whyHot: "Small-space living is structural in EU metros. Folding design keeps freight cost per unit tiny.",
    buyerTip: "Verify load rating with your own test (claimed 220lb often isn't). Clear-window + wheels variant commands premium."
  },
  {
    id: "p011",
    name: "Sonic Electric Toothbrush (Gift Box)",
    track: "Beauty & Personal Care",
    emoji: "🪥",
    factoryPrice: [7.5, 15.0],
    retailPrice: [39.99, 69.99],
    moq: 500,
    trendScore: 86,
    saturation: "high",
    signals: ["Brush-head refill backend", "Holiday gift box performer", "Subscription potential"],
    certifications: ["FDA 510(k) exempt check", "FCC", "CE/RoHS", "IPX7 report"],
    logistics: "Small parcel · battery docs for air",
    seasonality: "Peaks Nov–Dec + Feb (Valentine's duo boxes)",
    whyHot: "Oral-care premiumization + a consumable backend (brush heads) that compounds with every sale.",
    buyerTip: "30-day battery life and IPX7 are table stakes. The duo gift box is the highest-converting SKU."
  },
  {
    id: "p012",
    name: "Ultralight Camping Moon Chair",
    track: "Outdoor & Garden",
    emoji: "🏕️",
    factoryPrice: [7.0, 14.0],
    retailPrice: [39.99, 69.99],
    moq: 500,
    trendScore: 85,
    saturation: "low",
    signals: ["Glamping trend", "Instagram-visual product", "Multi-unit family orders"],
    certifications: ["CE (general)", "REACH (fabrics/coatings)"],
    logistics: "Sea freight · compact carry bag",
    seasonality: "Mar–Sep; order Nov–Jan",
    whyHot: "Aesthetic camping content keeps this category compounding. Households buy 2–4 at once.",
    buyerTip: "7075 aluminum frame, ≥330lb rating, ≤4.4lb packed — hit all three or reviews will find you."
  },
  {
    id: "p013",
    name: "Open-Ear TWS Earbuds",
    track: "Consumer Electronics",
    emoji: "🎧",
    factoryPrice: [4.5, 12.0],
    retailPrice: [25.99, 59.99],
    moq: 1000,
    trendScore: 90,
    saturation: "high",
    signals: ["Open-ear form factor rising", "Runner/cyclist niche", "Mature supply chain"],
    certifications: ["FCC", "CE/RoHS", "UN38.3", "BT SIG (logo use)"],
    logistics: "Small parcel · battery docs",
    seasonality: "Year-round; Jan fitness spike",
    whyHot: "Open-ear is the last un-commoditized TWS niche — safety-while-running angle gives a real ad hook.",
    buyerTip: "Skip generic in-ear TWS (race to the bottom). Open-ear clip design + BT5.3 + ≤60ms game mode differentiates."
  },
  {
    id: "p014",
    name: "Self-Heating Hot Pot Kit",
    track: "Food & Beverage",
    emoji: "🍲",
    factoryPrice: [1.8, 3.5],
    retailPrice: [9.99, 16.99],
    moq: 2000,
    trendScore: 80,
    saturation: "low",
    signals: ["Asian-food TikTok wave", "Novelty + repeat combo", "Ethnic grocery expansion"],
    certifications: ["FDA food facility registration", "US customs prior notice", "Heating element transport rules"],
    logistics: "Sea freight · check heating-pack air restrictions",
    seasonality: "Oct–Mar comfort-food peak",
    whyHot: "The self-heating demo is inherently viral; Western Gen-Z discovery of Chinese convenience food is early innings.",
    buyerTip: "Import compliance (FDA + heating packs) is the barrier — clear it and competition thins dramatically."
  },
  {
    id: "p015",
    name: "Dual-Motor Standing Desk Frame",
    track: "Home & Office",
    emoji: "🪑",
    factoryPrice: [60, 110],
    retailPrice: [199, 399],
    moq: 100,
    trendScore: 78,
    saturation: "medium",
    signals: ["Hybrid-work structural demand", "High AOV, low return rate", "B2B office refits"],
    certifications: ["UL/ETL (US)", "CE/EMC", "BIFMA test report"],
    logistics: "Sea freight only · heavy, palletized",
    seasonality: "Year-round; Sep + Jan office cycles",
    whyHot: "High ticket with healthy margin and sticky B2B repeat orders — the anti-race-to-bottom pick.",
    buyerTip: "Dual motor + memory presets + ≤50dB. UL/ETL cert is mandatory for US retail channels."
  },
  {
    id: "p016",
    name: "Screen-Free Kids Story Player",
    track: "Baby & Toys",
    emoji: "🧸",
    factoryPrice: [6.0, 13.0],
    retailPrice: [34.99, 69.99],
    moq: 500,
    trendScore: 82,
    saturation: "low",
    signals: ["Screen-time anxiety trend", "Parent-community virality", "Gift registry item"],
    certifications: ["CPSIA + ASTM F963 (US)", "EN71 + CE (EU)", "FCC"],
    logistics: "Small parcel · toy cert docs required at customs",
    seasonality: "Nov–Dec dominant + birthday long tail",
    whyHot: "Rides the anti-screen parenting wave; audio content model mirrors the Toniebox success story in DACH.",
    buyerTip: "Toy certifications are non-negotiable and slow — start EN71/ASTM testing before your first PO."
  },
  {
    id: "p017",
    name: "Magnetic Car Phone Mount (N52)",
    track: "Auto Accessories",
    emoji: "🚗",
    factoryPrice: [1.6, 4.0],
    retailPrice: [14.99, 24.99],
    moq: 1000,
    trendScore: 87,
    saturation: "high",
    signals: ["Evergreen car staple", "Ad-friendly economics", "Amazon high-velocity"],
    certifications: ["CE/RoHS (if LED/wireless charge variant)"],
    logistics: "Small parcel · featherweight, cheap to ship",
    seasonality: "Year-round flat",
    whyHot: "Tiny, cheap to ship, universally needed — a classic paid-ads volume machine.",
    buyerTip: "≥6 genuine N52 magnets and a metal (not plastic) ball joint — the two specs behind every 1-star review."
  },
  {
    id: "p018",
    name: "Modernized Mamian (Horse-Face) Skirt",
    track: "Apparel & Accessories",
    emoji: "👘",
    factoryPrice: [12.0, 30.0],
    retailPrice: [59.99, 129.99],
    moq: 200,
    trendScore: 88,
    saturation: "low",
    signals: ["New-Chinese-style fashion export", "Diaspora + fashion-forward buyers", "Museum-collab aesthetic"],
    certifications: ["OEKO-TEX preferred", "Fiber-content labeling (FTC/EU)"],
    logistics: "Air or sea · low weight, high value density",
    seasonality: "Year-round; Lunar New Year + wedding season spikes",
    whyHot: "Heritage silhouette adapted for daily wear — a story-rich product Western fast fashion can't copy credibly.",
    buyerTip: "Jacquard weave quality and pleat count define the tier. Office-friendly lengths move fastest overseas."
  },
  {
    id: "p019",
    name: "Countertop Ice Cream Maker (Compressor)",
    track: "Home & Kitchen",
    emoji: "🍦",
    factoryPrice: [45, 85],
    retailPrice: [149, 249],
    moq: 200,
    trendScore: 75,
    saturation: "low",
    signals: ["Homemade-dessert content", "Family/summer gifting", "Premium kitchen trend"],
    certifications: ["UL/ETL (US)", "CE/LVD", "FDA food contact", "refrigerant transport docs"],
    logistics: "Sea freight · fragile, compressor handling",
    seasonality: "Apr–Aug; order Dec–Feb",
    whyHot: "No-prefreeze compressor models leapfrog the frozen-bowl generation — a clear premium upgrade story.",
    buyerTip: "Compressor units need UL and careful freight, but sidestep the saturated bowl-style price war entirely."
  },
  {
    id: "p020",
    name: "8-Electrode Smart Body Scale",
    track: "Sports & Health",
    emoji: "⚖️",
    factoryPrice: [4.5, 11.0],
    retailPrice: [24.99, 49.99],
    moq: 1000,
    trendScore: 81,
    saturation: "medium",
    signals: ["App-ecosystem lock-in", "New Year fitness spike", "Gift performer"],
    certifications: ["FCC", "CE/RoHS", "GDPR-compliant app for EU"],
    logistics: "Small parcel · glass platform, drop-test packaging",
    seasonality: "Dec–Feb dominant",
    whyHot: "8-electrode upgrade gives a spec story over legacy 4-electrode scales flooding the market.",
    buyerTip: "The app IS the product: demand white-label app with EN/DE/FR/ES localization and GDPR data hosting."
  },
  {
    id: "p021",
    name: "Handheld UV Mattress Vacuum",
    track: "Home & Kitchen",
    emoji: "🛏️",
    factoryPrice: [9.0, 18.0],
    retailPrice: [49.99, 89.99],
    moq: 500,
    trendScore: 79,
    saturation: "medium",
    signals: ["Allergy-awareness content", "Before/after demo virality", "Parent audience"],
    certifications: ["FCC", "CE/RoHS", "UV safety interlock report"],
    logistics: "Mid parcel · sea for margin",
    seasonality: "Spring (allergy) + fall peaks",
    whyHot: "Invisible-dust-mite demo content is conversion gold with allergy-conscious Western parents.",
    buyerTip: "UV auto-shutoff interlock is a legal must in EU. Visible dust-cup design boosts perceived efficacy."
  },
  {
    id: "p022",
    name: "Pocket Photo Printer (Thermal)",
    track: "Consumer Electronics",
    emoji: "📸",
    factoryPrice: [16.0, 32.0],
    retailPrice: [59.99, 99.99],
    moq: 300,
    trendScore: 77,
    saturation: "low",
    signals: ["Journaling/scrapbook trend", "Paper-refill backend", "Teen gifting"],
    certifications: ["FCC", "CE/RoHS", "UN38.3"],
    logistics: "Small parcel · battery docs",
    seasonality: "Nov–Dec + graduation season",
    whyHot: "Ink-free thermal printing keeps costs tiny while the sticker-paper refill backend compounds.",
    buyerTip: "App template library drives retention — license one with EN/EU language packs. Bundle 3 paper rolls."
  },
  {
    id: "p023",
    name: "Cat Scratcher Lounge (Corrugated)",
    track: "Pet Supplies",
    emoji: "🐾",
    factoryPrice: [3.5, 8.0],
    retailPrice: [22.99, 39.99],
    moq: 500,
    trendScore: 76,
    saturation: "low",
    signals: ["Consumable = repeat orders", "Design-differentiation space", "Chewy/Amazon steady"],
    certifications: ["Non-toxic glue report (pet safety)"],
    logistics: "Sea freight · bulky but light, flat-pack designs win",
    seasonality: "Year-round flat",
    whyHot: "Cardboard wears out — built-in repurchase cycle. Novel shapes routinely go viral on pet TikTok.",
    buyerTip: "High-density corrugate + ≥16in width minimizes returns. Include catnip sachet; it's expected."
  },
  {
    id: "p024",
    name: "Astronaut Galaxy Projector",
    track: "Home & Office",
    emoji: "🌌",
    factoryPrice: [6.5, 13.0],
    retailPrice: [29.99, 59.99],
    moq: 500,
    trendScore: 85,
    saturation: "high",
    signals: ["TikTok room-decor evergreen", "Teen gifting monster", "Q4 volume spike"],
    certifications: ["FCC", "CE/RoHS", "laser class documentation"],
    logistics: "Small parcel · air-friendly",
    seasonality: "Oct–Dec is 60% of annual volume",
    whyHot: "Room-aesthetic content on TikTok keeps resurrecting this SKU every Q4 — a proven gifting machine.",
    buyerTip: "Laser class ≤1 documentation matters for EU customs. Remote + timer + Bluetooth speaker variant wins carts."
  }
];

const TRACKS = [
  "All Tracks",
  "Consumer Electronics",
  "Home & Kitchen",
  "Home & Office",
  "Beauty & Personal Care",
  "Apparel & Accessories",
  "Outdoor & Garden",
  "Sports & Health",
  "Pet Supplies",
  "Baby & Toys",
  "Auto Accessories",
  "Food & Beverage"
];
